title: Malick
logo: /assets/img/headshot.jpg
description: Full Stack Developer & Devops <br /><br /> ğŸŒ Dakar, SÃ©negal <br /> âœ‰ï¸ malick.developer@gmail.com
show_dowloads: false
theme: jekyll-theme-minimal
author:
  location: Paris, France
