title: Malick
logo: /assets/img/headshot.jpg
description: Full Stack Developer & Devops <br /><br /> ğŸŒ Dakar, SÃ©negal <br /> âœ‰ï¸ malick.developer@gmail.com <br> [![Twitter](https://badgen.net/badge/icon/twitter?icon=twitter&label)](https://twitter.com/malick_yacine)
show_dowloads: false
theme: jekyll-theme-minimal
author:
  location: Paris, France
