title: Malick
logo: /assets/img/headshot.jpg
description: Full Stack Developer & Devops <br /><br /> ğŸŒ Dakar, SÃ©negal <br /> âœ‰ï¸ malick.developer@gmail.com <br /><br /> <a href="https://www.linkedin.com/in/malickdev" target="_blank" rel="noreferrer"><img class="linkedin" src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/linkedin.svg" width="32" height="32" /></a><br /><a href="https://twitter.com/malick_yacine" target="_blank" rel="noreferrer"><img class="twitter" src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/twitter.svg" width="32" height="32" />
</a>
show_dowloads: false
theme: jekyll-theme-minimal
