title: Malick
logo: /assets/img/headshot.jpg
description: Full Stack Developer & Devops \ * ğŸŒ  I'm based in Dakar
* âœ‰ï¸  You can contact me at [malick.developer@gmail.com](mailto:malick.developer@gmail.com)
show_dowloads: false
theme: jekyll-theme-minimal
author:
  location: Paris, France
